#  ansible-playbook --limit <HOSTGROUP> nxos_desc.yml -k
#
#  Since ansible 2.6 prompt for hostgroup should work as expected again.
 
---
- name: Playbook NX-OS Show all Interfaces with specific Description
  vars_prompt :
#    - name: "prompted_hostgroup"
#      prompt: "Enter hostgroup (osha, osdd, ...) to play with, default:"
#      private: no
#      default: "osdd"
    - name: "desc"
      prompt: "Enter string to search for"
      private: no
  hosts: all
  gather_facts: false
  connection: network_cli
 
  tasks:
 
  - name: show interface description
    nxos_command:
      commands: show interface descr | incl {{ desc }}
    register: result
 
  - debug:
      msg: "{{ result.stdout_lines[0] }}"
    when: result.stdout[0] != ""
