---
- name: Query for connected hosts via ifDesc and CDP/LLDP learnings
  hosts: all
  gather_facts: yes
  connection: network_cli
  vars_prompt:
    - name: "query"
      prompt: "Enter query"
      private: no

  tasks:

    - name: Find query string in net_neighbors
      lineinfile:
        path: ~/{{ query }}.txt
        line: "[{{ inventory_hostname }}] {{item.key}} via CDP/LLDP [{{ item.value[0].host }}]"
        create: yes
      loop: "{{ ansible_facts.net_neighbors | dict2items }}"
      loop_control:
        label: "{{ item.key }} Neighbor: {{ item.value[0].host }}"
      when: query in item.value[0].host

    - name: Find query string in net_interfaces
      lineinfile:
        path: ~/{{ query }}.txt
        line: "[{{ inventory_hostname }}] {{item.key}} via IfDesc: [{{ item.value.description }}]"
        create: yes
      loop: "{{ ansible_facts.net_interfaces | dict2items }}"
      loop_control:
        label: "{{ item.key }} ifDesc: {{ item.value.description }}"
      when: item.value.description is defined and item.value.description and query in item.value.description
